[tool.poetry]
name = "forge"
version = "0.13.0"
description = "Quickly build a professional web app using Django."
authors = ["Dave Gaeddert <dave.gaeddert@dropseed.dev>"]
license = "MIT"
readme = "README.md"
homepage = "https://www.forgepackages.com/"
documentation = "https://www.forgepackages.com/docs/"
repository = "https://github.com/forgepackages/forge"
keywords = ["django", "saas", "forge", "framework"]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[tool.poetry.scripts]
forge = "forge.cli:cli"

[tool.poetry.dependencies]
python = "^3.8"

forge-core = "^0.1.0"
forge-format = "^0.1.0"
forge-work = "^0.1.0"

Django = "^4.0"
django-widget-tweaks = "^1.4.12"
dj-database-url = "^0.5.0"
whitenoise = "^6.0.0"

python-dotenv = "^0.20.0"
psycopg2-binary = "^2.9.2"
gunicorn = "^20.1.0"
click = "^8.1.0"

# For Redis caching (the suggested default)
redis = "^4.2.2"
hiredis = "^2.0.0"

# Techinically dev dependencies...
# but would have to decalre that in child for that to work
# Helpful to have ipdb in production shell anyway? Anything wrong with this?
ipdb = "^0.13.9"
pytest = "^7.0.0"
pytest-django = "^4.5.2"

requests = ">=2.0.0"
click-didyoumean = "^0.3.0"


[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
