#!/bin/sh -e
poetry run black forgepro --exclude migrations "$@"
poetry run isort forgepro --skip    migrations --profile black "$@"

poetry run black tests "$@"
poetry run isort tests --profile black "$@"
