name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.4
        ports: ["5432:5432/tcp"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    steps:
    - run: sudo apt update && sudo apt install libpq-dev
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: poetry
    - name: Install dependencies
      env:
        POETRY_HTTP_BASIC_FORGEPACKAGES_USERNAME: ${{ secrets.FORGEPACKAGES_PROJECT }}
        POETRY_HTTP_BASIC_FORGEPACKAGES_PASSWORD: ${{ secrets.FORGEPACKAGES_TOKEN }}
      run: |
        poetry env use 3.9
        poetry install
    - name: Test
      run: poetry run forge test
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        DEBUG: true
        SECRET_KEY: testing
        BASE_URL: http://example.com
        STRIPE_PRICE_ID: testing
        GITHUB_APP_INSTALLATION_ID: 0
        GITHUB_APP_ID: 0
        GITHUB_APP_PRIVATE_KEY: testing
