name: deps

on:
  schedule:
  - cron: 0 0 1 * *
  workflow_dispatch: {}

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: poetry
    - name: Install dependencies
      env:
        POETRY_HTTP_BASIC_FORGEPACKAGES_USERNAME: ${{ secrets.FORGEPACKAGES_PROJECT }}
        POETRY_HTTP_BASIC_FORGEPACKAGES_PASSWORD: ${{ secrets.FORGEPACKAGES_TOKEN }}
      run: |
        poetry env use 3.9
        poetry install
    - name: Install deps
      run: curl https://deps.app/install.sh | bash -s -- -b $HOME/bin
    - name: Run deps
      run: $HOME/bin/deps ci
      env:
        DEPS_TOKEN: ${{ secrets.DEPS_TOKEN }}
        DEPS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
